### ISSUE TITLE
Get rid of config file

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/check-my-repo#137]
It seems that the config file how it is right now, e.g.

```json
{
  "owner": "saucelabs",
  "pagination": 100,
  "action-user-name": "OSS Check My Repo",
  "action-email": "oss-check-my-repo-bot@users.noreply.github.com"
}
```

Seems obsolete. The owner is given by the organisation name and the pagination is something user should not worry about. If folks want to update the action user name or email they can also directly define that in the GitHub action. If we can avoid having to update a config it makes adopting this tool more easier.

**Comment by discombobulateme** [comment]
@christian-bromann this meant to be fields that enables user to configure/ change the parameters. 
Owner goes both for organization or user, but it's just a name... I can change to user :) other fields there's no need to change.
My question is: if user is the only option, why having a config file? Should we just don't have it?

**Comment by christian-bromann** [comment]
> Should we just don't have it?

Yes, that is what I am suggestion. The owner (either org or user) can be taken from environment variables that GitHub provides you. The rest of these options can be just modified directly in their files. Also I think `pagination` is nothing a user would be interested to change.

**Comment by discombobulateme** [comment]
Schon gemacht! 🥳
